#!/bin/bash

#Rich H install script. This script is placed on the desktop embedded in the custom installer.
#Installs git and Xdotools. Sets WIFI to VoyMobile network. Clones the GitHub repo, changes the permissions
#and runs the setup script.

# Set wifi to voyMobile

SSID=VOYMobile
PASSWORD=SDDBkPBRbBS8EVjjBrqFyn4IxY2v

# Create a new Wi-Fi connection
nmcli connection add type wifi con-name "WiFi" ifname "*" ssid "$SSID" -- wifi-sec.key-mgmt wpa-psk wifi-sec.psk "$PASSWORD"

# Check the exit status of the previous command
if [ $? -eq 0 ]; then
  # Set the connection to auto-connect
  nmcli connection modify "WiFi" connection.autoconnect yes
  
  # Check the exit status of the previous command
  if [ $? -eq 0 ]; then
    # Display a success message
    zenity --info --text="Wi-Fi connection setup succeeded." --width=500
  else
    # Display an error message
    zenity --error --text="Error setting Wi-Fi connection to auto-connect." --width=500
  fi
else
  # Display an error message
  zenity --error --text="Error creating Wi-Fi connection." --width=500
fi


run_command() {
  if sudo -n true 2>/dev/null; then
    # No password prompt needed, can run the command with sudo directly
    sudo "$@"
  else
    # Password is needed, prompt the user for it using Zenity
    password=$(zenity --password --title="Enter the password for sudo" --width=500)
    # Check if the user canceled the password entry
    if [[ $? -ne 0 ]]; then
      zenity --error --text="Password entry canceled. Exiting..."
      exit 1
    fi
    # Execute the command with sudo using the password provided by the user
    echo "$password" | sudo -S "$@"
  fi
}
# Install Git (if not already installed)
if ! command -v git &> /dev/null; then
   run_command sudo apt install -y git
   zenity --info --text="Git is installed."  --width=500 

 fi

# Clone the repository
USERNAME="hamiltonrich"
REPO="voyKiosk"
CLONE_DIR="/home/voyage/Desktop/voykiosk"  # Change this to the desired directory name

if [ ! -d "$CLONE_DIR" ]; then
    git clone "https://github.com/$USERNAME/$REPO.git" "$CLONE_DIR"
else
    zenity --info --text="directory $CLONE_DIR already exists. Skipping clone."
fi

chmod +x /home/voyage/Desktop/voyKiosk/setup.sh
chmod +x /home/voyage/Desktop/voyKiosk/kiosk.sh
zenity --info --text="File permissions changed" --width=500


# Run setup script
bash /home/voyage/voyKiosk/setup.sh
